// generated by slang.py DO NOT EDIT
#pragma once

#define BORDER_VERTEX_BUF_clrs 2
#define BORDER_VERTEX_BUFSZ_clrs 36u
#define BORDER_VERTEX_BUF_globalParams 0
#define BORDER_VERTEX_BUFSZ_globalParams 4u
#define BORDER_VERTEX_BUF_glt 1
#define BORDER_VERTEX_BUFSZ_glt 1024u
#define BORDER_VERTEX_ATTR_rect 0
#define BORDER_VERTEX_ATTR_rect_color 1
#define BORDER_VERTEX_ATTR_BUFFER 3

#define KITTY_SLANG_VERTEX_SHADERS 1
